### PR TITLE
fix(a11y): move aria-label from svg icon to button

### LINKED ISSUE #2639: [fix] nav buttons ahould always have aria-label attributes
**ReactUSWDS Version & USWDS Version:**

* ReactUSWDS: 5.5.0
* USWDS: 3.6.0

**Describe the bug**

[WCAG § 4.1.2](https://www.w3.org/TR/WCAG21/#name-role-value) states the following:

> For all [user interface components](https://www.w3.org/TR/WCAG21/#dfn-user-interface-components) (including but not limited to: form elements, links and components generated by scripts), the [name](https://www.w3.org/TR/WCAG21/#dfn-name) and [role](https://www.w3.org/TR/WCAG21/#dfn-role) can be [programmatically determined](https://www.w3.org/TR/WCAG21/#dfn-programmatically-determinable); states, properties, and values that can be set by the user can be [programmatically set](https://www.w3.org/TR/WCAG21/#dfn-programmatically-set); and notification of changes to these items is available to [user agents](https://www.w3.org/TR/WCAG21/#dfn-user-agents), including [assistive technologies](https://www.w3.org/TR/WCAG21/#dfn-assistive-technologies).

The `NavCloseButton` element, while it accepts an `aria-label` itself, by default only applies an `aria-label` to the enclosed `Icon.Close` rather than the `<button />` element. This means that using any further abstracted components (like `ExtendedNav`) will cause the resulting HTML to violate this rule.

The buttons within the modal elements already conform to this paradigm, only the nav elements appear to be effected.

**To Reproduce**

1. Go to the project storybook
2. Click on Components -> Header
3. Inspect any `*Button` element
4. Observe that `aria-label` is not present on button elements, but is present on child `<svg />` elements

**Expected behavior**

`<button />` elements should have `aria-label` attribute to meet WCAG § 4.1.2 requirements.

**Additional context**

This issue was initially identified using [HTML_Codesniffer](https://github.com/squizlabs/HTML_CodeSniffer) which we use alongside Axe and playwright to implement E2E testing.

### PR DESCRIPTION
**Pull request by seevee**
# Summary

## Related Issues or PRs

Closes #2639 

## How To Test

I tested with `yarn link` to an application using playwright, AXE, and HTML_CodeSniffer. I am yet not familiar enough with these packages to set up an example repo, but I can confirm that these changes address our E2E testing issues.

### CODE REVIEW

**Comment by brandonlenz** [comment]
Thanks for the PR!

This is conflicting with the last change to this component in https://github.com/trussworks/react-uswds/pull/2500

@sawyerh do you have thoughts on this change since you authored the last iteration?

**Comment by sawyerh** [comment]
@brandonlenz Hey stranger 😄  No issues from my side. I think my original solution was based on the USWDS example code which uses an `alt` on their `img`, but this solution seems like it should be fine too.

CleanShot 2023-10-25 at 15 16 29@2x

**Comment by seevee** [comment]
Some additional context - these changes will bring the NavCloseButton default behavior closer to parity with  ModalCloseButton:
https://github.com/trussworks/react-uswds/blob/59dffd138f745f38a222523360a4666c0c13b030/src/components/Modal/ModalCloseButton/ModalCloseButton.tsx#L14-L24

The aria-label being present on the svg within the button is probably not hugely different from applying it directly to the button, except that our a11y tests can't seem to drill down into the svg as content to satisfy the button requirements. See this error message when using the ExtendedNav default:

```
WCAG2AA.Principle4.Guideline4_1.4_1_2.H91.Button.Name

This button element does not have a name available to an accessibility API. Valid names are: title undefined, element content, aria-label undefined, aria-labelledby undefined.
```

**Comment by brandonlenz** [comment]
> EDIT: would it be acceptable to add an `alt="Close"` to the icon properties alongside the button's `aria-label="Close"`? That seems like it should let us satisfy both the svg-img-alt rule from https://accessibilityinsights.com as well as the Button.Name rule from our AXE/Playwright setup.

@seevee I _think_ that sounds fine. @shkeating this one is pretty accessibility focused. Do you have any thoughts about the changes or suggestion?

File: src/components/header/NavCloseButton/NavCloseButton.tsx [hunk 1]
```diff
@@ -15,9 +15,10 @@ export const NavCloseButton = ({
       className={classes}
       onClick={onClick}
       data-testid="navCloseButton"
+      aria-label="Close"
       {...buttonProps}
       type="button">
-      <Icon.Close size={3} aria-label="Close" />
```
Comment (shkeating) [inline src/components/header/NavCloseButton/NavCloseButton.tsx:20]: this is an acceptable implementation to me, my ANDI output (which shows the text data that is received by screen readers visually) shows the close button labelled as 'Close' as intended. 

image


However, I would encourage you to get more specific in the accessible name. Let's say we had another component in a page layout that also had a close icon. If both are named "close" they would be indistinguishable for a screen reader user navigating by links on a page.

the aria label is correct but I would change it to "close menu" or "close navigation" to avoid duplicate accessible names. If there was two components using close buttons under this pattern in the same page layout, we would see this ANDI error: [⚠ Non-unique button: same name/description as another button](https://www.ssa.gov/accessibility/andi/help/alerts.html?non_unique_button).

**Review by shkeating — CHANGES_REQUESTED** [review]

File: src/components/header/NavCloseButton/NavCloseButton.tsx (hunk 1 above)
Comment (brandonlenz) [reply src/components/header/NavCloseButton/NavCloseButton.tsx:20]: What about enabling the prop to be passed in? 

Whatever default value we provide here, whether "close" or "close menu" might be nice to have the option to override it. That would require an `iconProps` param passed in where we could then get `iconProps['aria-label']`, and if present, use that instead of the default.

I'm fine with that being an enhancement later on too though.

Comment (seevee) [reply src/components/header/NavCloseButton/NavCloseButton.tsx:20]: @shkeating thanks for the review and the advice! I've updated the `aria-label` to `"Close Navigation Menu"` to make it more unique and descriptive.

@brandonlenz Allowing the label to be passed in as a prop sounds like the ideal path to me! I think this would be especially useful if we want to show localized aria labels.

I think there's a couple of other components that could use that enhancement as well, so I'll keep the diff on this PR as lean as possible for now and open a new PR targeted at using those props as overrides. Let me know if that works!

Comment (brandonlenz) [reply src/components/header/NavCloseButton/NavCloseButton.tsx:20]: That works for me.

**Review by brandonlenz — DISMISSED** [review]

**Review by brandonlenz — DISMISSED** [review]

**Comment by seevee** [comment]
@brandonlenz apologies for the churn on this, looks like we can't add an `alt` attribute to an svg.

**Comment by brandonlenz** [comment]
@seevee no worries! Thanks for seeing it through

**Comment by brandonlenz** [comment]
I think we'll need @shkeating to give it another approval anyways since she requested changes

**Review by shkeating — APPROVED** [review]

**Comment by shkeating** [comment]
all set! great work all!
